// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: event.proto

#include "event.pb.h"
#include "event.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace Event {

static const char* IrohaConnection_method_names[] = {
  "/Event.IrohaConnection/Operation",
};

std::unique_ptr< IrohaConnection::Stub> IrohaConnection::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< IrohaConnection::Stub> stub(new IrohaConnection::Stub(channel));
  return stub;
}

IrohaConnection::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Operation_(IrohaConnection_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status IrohaConnection::Stub::Operation(::grpc::ClientContext* context, const ::Event::ConsensusEvent& request, ::Event::StatusResponse* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_Operation_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::Event::StatusResponse>* IrohaConnection::Stub::AsyncOperationRaw(::grpc::ClientContext* context, const ::Event::ConsensusEvent& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::Event::StatusResponse>(channel_.get(), cq, rpcmethod_Operation_, context, request);
}

IrohaConnection::Service::Service() {
  (void)IrohaConnection_method_names;
  AddMethod(new ::grpc::RpcServiceMethod(
      IrohaConnection_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< IrohaConnection::Service, ::Event::ConsensusEvent, ::Event::StatusResponse>(
          std::mem_fn(&IrohaConnection::Service::Operation), this)));
}

IrohaConnection::Service::~Service() {
}

::grpc::Status IrohaConnection::Service::Operation(::grpc::ServerContext* context, const ::Event::ConsensusEvent* request, ::Event::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Event

