// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: event.proto
#ifndef GRPC_event_2eproto__INCLUDED
#define GRPC_event_2eproto__INCLUDED

#include "event.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace Event {

class IrohaConnection GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Operation(::grpc::ClientContext* context, const ::Event::ConsensusEvent& request, ::Event::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Event::StatusResponse>> AsyncOperation(::grpc::ClientContext* context, const ::Event::ConsensusEvent& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Event::StatusResponse>>(AsyncOperationRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Event::StatusResponse>* AsyncOperationRaw(::grpc::ClientContext* context, const ::Event::ConsensusEvent& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Operation(::grpc::ClientContext* context, const ::Event::ConsensusEvent& request, ::Event::StatusResponse* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Event::StatusResponse>> AsyncOperation(::grpc::ClientContext* context, const ::Event::ConsensusEvent& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Event::StatusResponse>>(AsyncOperationRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::Event::StatusResponse>* AsyncOperationRaw(::grpc::ClientContext* context, const ::Event::ConsensusEvent& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_Operation_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Operation(::grpc::ServerContext* context, const ::Event::ConsensusEvent* request, ::Event::StatusResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Operation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Operation() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Operation() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Operation(::grpc::ServerContext* context, const ::Event::ConsensusEvent* request, ::Event::StatusResponse* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOperation(::grpc::ServerContext* context, ::Event::ConsensusEvent* request, ::grpc::ServerAsyncResponseWriter< ::Event::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Operation<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Operation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Operation() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Operation() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Operation(::grpc::ServerContext* context, const ::Event::ConsensusEvent* request, ::Event::StatusResponse* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace Event


#endif  // GRPC_event_2eproto__INCLUDED
