#ifndef CORE_VALIDATION_TRANSACTIONVALIDATOR_HPP_
#define CORE_VALIDATION_TRANSACTIONVALIDATOR_HPP_

namespace transactionValidator {
  //TODO:
};

#endif  // CORE_VALIDATION_TRANSACTIONVALIDATOR_HPP_
