// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENDPOINT_IROHA_H_
#define FLATBUFFERS_GENERATED_ENDPOINT_IROHA_H_

#include "flatbuffers/flatbuffers.h"

#include "account_generated.h"
#include "asset_generated.h"
#include "commands_generated.h"
#include "key_generated.h"
#include "main_generated.h"
#include "primitives_generated.h"
#include "transaction_generated.h"

namespace iroha {

struct DummyForGenerateEndpint_generated_h;

struct DummyForGenerateEndpint_generated_h FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct DummyForGenerateEndpint_generated_hBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  DummyForGenerateEndpint_generated_hBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  DummyForGenerateEndpint_generated_hBuilder &operator=(const DummyForGenerateEndpint_generated_hBuilder &);
  flatbuffers::Offset<DummyForGenerateEndpint_generated_h> Finish() {
    const auto end = fbb_.EndTable(start_, 0);
    auto o = flatbuffers::Offset<DummyForGenerateEndpint_generated_h>(end);
    return o;
  }
};

inline flatbuffers::Offset<DummyForGenerateEndpint_generated_h> CreateDummyForGenerateEndpint_generated_h(
    flatbuffers::FlatBufferBuilder &_fbb) {
  DummyForGenerateEndpint_generated_hBuilder builder_(_fbb);
  return builder_.Finish();
}

}  // namespace iroha

#endif  // FLATBUFFERS_GENERATED_ENDPOINT_IROHA_H_
