/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class repository_DomainRepository */

#ifndef _Included_repository_DomainRepository
#define _Included_repository_DomainRepository
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     repository_DomainRepository
 * Method:    add
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_repository_DomainRepository_add__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     repository_DomainRepository
 * Method:    add
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_repository_DomainRepository_add__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     repository_DomainRepository
 * Method:    add
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_repository_DomainRepository_add__Ljava_lang_String_2J
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     repository_DomainRepository
 * Method:    add
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_repository_DomainRepository_add__Ljava_lang_String_2D
  (JNIEnv *, jclass, jstring, jdouble);

/*
 * Class:     repository_DomainRepository
 * Method:    findOne
 * Signature: (Ljava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_repository_DomainRepository_findOne
  (JNIEnv *, jclass, jstring);

/*
 * Class:     repository_DomainRepository
 * Method:    update
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_repository_DomainRepository_update
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     repository_DomainRepository
 * Method:    remove
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_repository_DomainRepository_remove
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
