/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class repository_Repository */

#ifndef _Included_repository_Repository
#define _Included_repository_Repository
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     repository_Repository
 * Method:    accountAdd
 * Signature: (Ljava/util/HashMap;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_repository_Repository_accountAdd
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     repository_Repository
 * Method:    accountAttach
 * Signature: (Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_accountAttach
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    accountUpdate
 * Signature: (Ljava/util/HashMap;[Ljava/lang/String;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_accountUpdate
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     repository_Repository
 * Method:    accountRemove
 * Signature: (Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_accountRemove
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    accountInfoFindByUuid
 * Signature: (Ljava/util/HashMap;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_accountInfoFindByUuid
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    accountValueFindByUuid
 * Signature: (Ljava/util/HashMap;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_repository_Repository_accountValueFindByUuid
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    accountExists
 * Signature: (Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_accountExists
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    domainAdd
 * Signature: (Ljava/util/HashMap;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_repository_Repository_domainAdd
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    domainUpdate
 * Signature: (Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_domainUpdate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    domainRemove
 * Signature: (Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_domainRemove
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    domainFindByUuid
 * Signature: (Ljava/util/HashMap;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_domainFindByUuid
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    domainExists
 * Signature: (Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_domainExists
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    assetAdd
 * Signature: (Ljava/util/HashMap;Ljava/util/HashMap;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_repository_Repository_assetAdd
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     repository_Repository
 * Method:    assetUpdate
 * Signature: (Ljava/util/HashMap;Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_assetUpdate
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     repository_Repository
 * Method:    assetRemove
 * Signature: (Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_assetRemove
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    assetInfoFindByUuid
 * Signature: (Ljava/util/HashMap;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_assetInfoFindByUuid
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    assetValueFindByUuid
 * Signature: (Ljava/util/HashMap;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_assetValueFindByUuid
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    assetExists
 * Signature: (Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_assetExists
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    simpleAssetAdd
 * Signature: (Ljava/util/HashMap;Ljava/util/HashMap;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_repository_Repository_simpleAssetAdd
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     repository_Repository
 * Method:    simpleAssetUpdate
 * Signature: (Ljava/util/HashMap;Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_simpleAssetUpdate
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     repository_Repository
 * Method:    simpleAssetRemove
 * Signature: (Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_simpleAssetRemove
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    simpleAssetInfoFindByUuid
 * Signature: (Ljava/util/HashMap;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_simpleAssetInfoFindByUuid
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    simpleAssetValueFindByUuid
 * Signature: (Ljava/util/HashMap;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_simpleAssetValueFindByUuid
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    simpleAssetExists
 * Signature: (Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_simpleAssetExists
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    peerAdd
 * Signature: (Ljava/util/HashMap;Ljava/util/HashMap;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_repository_Repository_peerAdd
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     repository_Repository
 * Method:    peerUpdate
 * Signature: (Ljava/util/HashMap;Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_peerUpdate
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     repository_Repository
 * Method:    peerRemove
 * Signature: (Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_peerRemove
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    peerInfoFindByUuid
 * Signature: (Ljava/util/HashMap;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_peerInfoFindByUuid
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    peerTrustFindByUuid
 * Signature: (Ljava/util/HashMap;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_peerTrustFindByUuid
  (JNIEnv *, jclass, jobject);

/*
 * Class:     repository_Repository
 * Method:    peerExists
 * Signature: (Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_peerExists
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
