/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class repository_DomainRepository */

#ifndef _Included_repository_DomainRepository
#define _Included_repository_DomainRepository
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     repository_DomainRepository
 * Method:    accountAdd
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_repository_DomainRepository_accountAdd
  (JNIEnv *, jclass, jstring, jstring, jobjectArray);

/*
 * Class:     repository_DomainRepository
 * Method:    accountAttach
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_DomainRepository_accountAttach
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     repository_DomainRepository
 * Method:    accountUpdate
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_DomainRepository_accountUpdate
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     repository_DomainRepository
 * Method:    accountRemove
 * Signature: (Ljava/lang/String;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_DomainRepository_accountRemove
  (JNIEnv *, jclass, jstring);

/*
 * Class:     repository_DomainRepository
 * Method:    accountInfoFindByUuid
 * Signature: (Ljava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_repository_DomainRepository_accountInfoFindByUuid
  (JNIEnv *, jclass, jstring);

/*
 * Class:     repository_DomainRepository
 * Method:    accountValueFindByUuid
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_repository_DomainRepository_accountValueFindByUuid
  (JNIEnv *, jclass, jstring);

/*
 * Class:     repository_DomainRepository
 * Method:    accountExists
 * Signature: (Ljava/lang/String;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_DomainRepository_accountExists
  (JNIEnv *, jclass, jstring);

/*
 * Class:     repository_DomainRepository
 * Method:    assetAdd
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/HashMap;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_repository_DomainRepository_assetAdd
  (JNIEnv *, jclass, jstring, jstring, jobject, jstring);

/*
 * Class:     repository_DomainRepository
 * Method:    assetUpdate
 * Signature: (Ljava/lang/String;Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_DomainRepository_assetUpdate
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     repository_DomainRepository
 * Method:    assetRemove
 * Signature: (Ljava/lang/String;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_DomainRepository_assetRemove
  (JNIEnv *, jclass, jstring);

/*
 * Class:     repository_DomainRepository
 * Method:    assetInfoFindByUuid
 * Signature: (Ljava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_repository_DomainRepository_assetInfoFindByUuid
  (JNIEnv *, jclass, jstring);

/*
 * Class:     repository_DomainRepository
 * Method:    assetValueFindByUuid
 * Signature: (Ljava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_repository_DomainRepository_assetValueFindByUuid
  (JNIEnv *, jclass, jstring);

/*
 * Class:     repository_DomainRepository
 * Method:    assetExists
 * Signature: (Ljava/lang/String;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_DomainRepository_assetExists
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
