/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class repository_Repository */

#ifndef _Included_repository_Repository
#define _Included_repository_Repository
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     repository_Repository
 * Method:    accountAdd
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_repository_Repository_accountAdd
  (JNIEnv *, jclass, jstring, jstring, jobjectArray);

/*
 * Class:     repository_Repository
 * Method:    accountAttach
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_accountAttach
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     repository_Repository
 * Method:    accountUpdate
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_accountUpdate
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     repository_Repository
 * Method:    accountRemove
 * Signature: (Ljava/lang/String;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_accountRemove
  (JNIEnv *, jclass, jstring);

/*
 * Class:     repository_Repository
 * Method:    accountInfoFindByUuid
 * Signature: (Ljava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_accountInfoFindByUuid
  (JNIEnv *, jclass, jstring);

/*
 * Class:     repository_Repository
 * Method:    accountValueFindByUuid
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_repository_Repository_accountValueFindByUuid
  (JNIEnv *, jclass, jstring);

/*
 * Class:     repository_Repository
 * Method:    accountExists
 * Signature: (Ljava/lang/String;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_accountExists
  (JNIEnv *, jclass, jstring);

/*
 * Class:     repository_Repository
 * Method:    assetAdd
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/HashMap;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_repository_Repository_assetAdd
  (JNIEnv *, jclass, jstring, jstring, jobject, jstring);

/*
 * Class:     repository_Repository
 * Method:    assetUpdate
 * Signature: (Ljava/lang/String;Ljava/util/HashMap;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_assetUpdate
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     repository_Repository
 * Method:    assetRemove
 * Signature: (Ljava/lang/String;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_assetRemove
  (JNIEnv *, jclass, jstring);

/*
 * Class:     repository_Repository
 * Method:    assetInfoFindByUuid
 * Signature: (Ljava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_assetInfoFindByUuid
  (JNIEnv *, jclass, jstring);

/*
 * Class:     repository_Repository
 * Method:    assetValueFindByUuid
 * Signature: (Ljava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_assetValueFindByUuid
  (JNIEnv *, jclass, jstring);

/*
 * Class:     repository_Repository
 * Method:    assetExists
 * Signature: (Ljava/lang/String;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_repository_Repository_assetExists
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
