#ifndef CORE_DOMAIN_SIGNATORYDELETETRANSACTION_HPP_
#define CORE_DOMAIN_SIGNATORYDELETETRANSACTION_HPP_

#include <msgpack.hpp>

namespace SignatoryDeleteTransaction {
  //TODO:
};

#endif  // CORE_DOMAIN_SIGNATORYDELETETRANSACTION_HPP_
